"""Initial migration with normalized buses

Revision ID: e546b165cd69
Revises: 
Create Date: 2025-09-06 01:08:56.065433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e546b165cd69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('buses', 'id',
               existing_type=sa.INTEGER(),
               comment='ID único del bus',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('buses', 'patente',
               existing_type=sa.VARCHAR(length=8),
               comment='Patente del vehículo formato chileno (6-8 caracteres)',
               existing_nullable=False)
    op.alter_column('buses', 'codigo_interno',
               existing_type=sa.VARCHAR(length=50),
               comment='Código interno de la empresa',
               existing_nullable=True)
    op.alter_column('buses', 'marca',
               existing_type=sa.VARCHAR(length=100),
               comment='Marca del vehículo',
               existing_nullable=False)
    op.alter_column('buses', 'modelo',
               existing_type=sa.VARCHAR(length=100),
               comment='Modelo del vehículo',
               existing_nullable=False)
    op.alter_column('buses', 'año',
               existing_type=sa.INTEGER(),
               comment='Año de fabricación',
               existing_nullable=False)
    op.alter_column('buses', 'numero_chasis',
               existing_type=sa.VARCHAR(length=17),
               comment='Número de chasis VIN (17 caracteres)',
               existing_nullable=True)
    op.alter_column('buses', 'numero_motor',
               existing_type=sa.VARCHAR(length=100),
               comment='Número del motor',
               existing_nullable=True)
    op.alter_column('buses', 'tipo_combustible_id',
               existing_type=sa.INTEGER(),
               comment='Referencia al tipo de combustible',
               existing_nullable=False)
    op.alter_column('buses', 'estado_id',
               existing_type=sa.INTEGER(),
               comment='Referencia al estado del bus',
               existing_nullable=False)
    op.alter_column('buses', 'capacidad_sentados',
               existing_type=sa.INTEGER(),
               comment='Número de asientos (máximo 45 según normativa)',
               existing_nullable=False)
    op.alter_column('buses', 'kilometraje_actual',
               existing_type=sa.INTEGER(),
               comment='Kilometraje actual del vehículo',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('buses', 'fecha_compra',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de compra del vehículo',
               existing_nullable=True)
    op.alter_column('buses', 'precio_compra',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Precio de compra en pesos',
               existing_nullable=True)
    op.alter_column('buses', 'observaciones',
               existing_type=sa.TEXT(),
               comment='Observaciones adicionales sobre el vehículo',
               existing_nullable=True)
    op.alter_column('buses', 'esta_activo',
               existing_type=sa.BOOLEAN(),
               comment='Indica si el registro está activo',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('buses', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de creación del registro',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('buses', 'fecha_actualizacion',
               existing_type=postgresql.TIMESTAMP(),
               comment='Fecha de última actualización',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('buses_codigo_interno_key'), 'buses', type_='unique')
    op.drop_constraint(op.f('buses_patente_key'), 'buses', type_='unique')
    op.create_index(op.f('ix_buses_codigo_interno'), 'buses', ['codigo_interno'], unique=True)
    op.create_index(op.f('ix_buses_id'), 'buses', ['id'], unique=False)
    op.create_index(op.f('ix_buses_patente'), 'buses', ['patente'], unique=True)
    op.alter_column('estados_buses', 'codigo',
               existing_type=sa.VARCHAR(length=20),
               comment='Código del estado: ACT, MAN, FS, RET',
               existing_nullable=False)
    op.alter_column('estados_buses', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               comment='Nombre del estado: Activo, Mantenimiento, etc.',
               existing_nullable=False)
    op.alter_column('estados_buses', 'descripcion',
               existing_type=sa.TEXT(),
               comment='Descripción detallada del estado',
               existing_nullable=True)
    op.alter_column('estados_buses', 'permite_asignacion',
               existing_type=sa.BOOLEAN(),
               comment='Si el bus puede ser asignado en este estado',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint(op.f('estados_buses_codigo_key'), 'estados_buses', type_='unique')
    op.create_index(op.f('ix_estados_buses_codigo'), 'estados_buses', ['codigo'], unique=True)
    op.create_index(op.f('ix_estados_buses_id'), 'estados_buses', ['id'], unique=False)
    op.alter_column('tipos_combustible', 'codigo',
               existing_type=sa.VARCHAR(length=10),
               comment='Código del combustible: DSL, GAS, ELE, HIB',
               existing_nullable=False)
    op.alter_column('tipos_combustible', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               comment='Nombre del combustible: Diesel, Gasolina, etc.',
               existing_nullable=False)
    op.alter_column('tipos_combustible', 'factor_emision',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment='Factor de emisión para cálculos ambientales',
               existing_nullable=True)
    op.drop_constraint(op.f('tipos_combustible_codigo_key'), 'tipos_combustible', type_='unique')
    op.create_index(op.f('ix_tipos_combustible_codigo'), 'tipos_combustible', ['codigo'], unique=True)
    op.create_index(op.f('ix_tipos_combustible_id'), 'tipos_combustible', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipos_combustible_id'), table_name='tipos_combustible')
    op.drop_index(op.f('ix_tipos_combustible_codigo'), table_name='tipos_combustible')
    op.create_unique_constraint(op.f('tipos_combustible_codigo_key'), 'tipos_combustible', ['codigo'], postgresql_nulls_not_distinct=False)
    op.alter_column('tipos_combustible', 'factor_emision',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               comment=None,
               existing_comment='Factor de emisión para cálculos ambientales',
               existing_nullable=True)
    op.alter_column('tipos_combustible', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Nombre del combustible: Diesel, Gasolina, etc.',
               existing_nullable=False)
    op.alter_column('tipos_combustible', 'codigo',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Código del combustible: DSL, GAS, ELE, HIB',
               existing_nullable=False)
    op.drop_index(op.f('ix_estados_buses_id'), table_name='estados_buses')
    op.drop_index(op.f('ix_estados_buses_codigo'), table_name='estados_buses')
    op.create_unique_constraint(op.f('estados_buses_codigo_key'), 'estados_buses', ['codigo'], postgresql_nulls_not_distinct=False)
    op.alter_column('estados_buses', 'permite_asignacion',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Si el bus puede ser asignado en este estado',
               existing_nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('estados_buses', 'descripcion',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Descripción detallada del estado',
               existing_nullable=True)
    op.alter_column('estados_buses', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Nombre del estado: Activo, Mantenimiento, etc.',
               existing_nullable=False)
    op.alter_column('estados_buses', 'codigo',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Código del estado: ACT, MAN, FS, RET',
               existing_nullable=False)
    op.drop_index(op.f('ix_buses_patente'), table_name='buses')
    op.drop_index(op.f('ix_buses_id'), table_name='buses')
    op.drop_index(op.f('ix_buses_codigo_interno'), table_name='buses')
    op.create_unique_constraint(op.f('buses_patente_key'), 'buses', ['patente'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('buses_codigo_interno_key'), 'buses', ['codigo_interno'], postgresql_nulls_not_distinct=False)
    op.alter_column('buses', 'fecha_actualizacion',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha de última actualización',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('buses', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha de creación del registro',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('buses', 'esta_activo',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Indica si el registro está activo',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('buses', 'observaciones',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Observaciones adicionales sobre el vehículo',
               existing_nullable=True)
    op.alter_column('buses', 'precio_compra',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Precio de compra en pesos',
               existing_nullable=True)
    op.alter_column('buses', 'fecha_compra',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Fecha de compra del vehículo',
               existing_nullable=True)
    op.alter_column('buses', 'kilometraje_actual',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Kilometraje actual del vehículo',
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('buses', 'capacidad_sentados',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Número de asientos (máximo 45 según normativa)',
               existing_nullable=False)
    op.alter_column('buses', 'estado_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Referencia al estado del bus',
               existing_nullable=False)
    op.alter_column('buses', 'tipo_combustible_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Referencia al tipo de combustible',
               existing_nullable=False)
    op.alter_column('buses', 'numero_motor',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Número del motor',
               existing_nullable=True)
    op.alter_column('buses', 'numero_chasis',
               existing_type=sa.VARCHAR(length=17),
               comment=None,
               existing_comment='Número de chasis VIN (17 caracteres)',
               existing_nullable=True)
    op.alter_column('buses', 'año',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Año de fabricación',
               existing_nullable=False)
    op.alter_column('buses', 'modelo',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Modelo del vehículo',
               existing_nullable=False)
    op.alter_column('buses', 'marca',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Marca del vehículo',
               existing_nullable=False)
    op.alter_column('buses', 'codigo_interno',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Código interno de la empresa',
               existing_nullable=True)
    op.alter_column('buses', 'patente',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='Patente del vehículo formato chileno (6-8 caracteres)',
               existing_nullable=False)
    op.alter_column('buses', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID único del bus',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
